### ISSUE TITLE
Not able to download pre-trained model and pre-processed dataset.

### ISSUE THREAD

**Issue by TejasDuseja** [redreamality/webke#1]
Hi,
I am not able to access pre-trained model and pre-processed dataset.  When trying to access link, it is giving me 'Secure Connection Failed' error.

**Comment by redreamality** [comment]
Thanks for your interest in our work.
The links are should be connected through http instead of https due to history reasons. 
I've also updated the links in readme, they should work now. 
Closing this issue, feel free to reopen it if any problem occurs.

**Comment by TejasDuseja** [comment]
Thanks. Able to access them now.

**Comment by wqwqqe** [comment]
Hello.
I find that the new link can't work now.

**Comment by redreamality** [comment]
> Hello. I find that the new link can't work now.

pls check ur netowork.
https://downforeveryoneorjustme.com/kw.fudan.edu.cn?proto=http
@wqwqqe

**Comment by owin2828** [comment]
Hello. @redreamality 
I am not able to access download 2 links below.

 - http://kw.fudan.edu.cn/resources/data/webke/webkedata.zip
 - http://kw.fudan.edu.cn/resources/data/webke/webkeweights.zip

Could you check this?

Thank you
