### ISSUE TITLE
Can not access data link

### ISSUE THREAD

**Issue by owin2828** [redreamality/webke#3]
Hello. @redreamality 
I am not able to access download 2 links below.

- http://kw.fudan.edu.cn/resources/data/webke/webkedata.zip
- http://kw.fudan.edu.cn/resources/data/webke/webkeweights.zip

Could you check this?

Thank you.

**Comment by redreamality** [comment]
Warning: Due to [GFW](https://en.wikipedia.org/wiki/Great_Firewall), the link above cannot always be accessed. Just wait several days and try again.
